# Site settings
title: my life as Greg &trade;
email: gregsadev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Greg a 27 year old Web Developer. This blog is all tea, all shade.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: greg0rys
github_username:  b0rnfly

# Build settings
markdown: kramdown
